# Generated by Django 6.1.1 on 2026-09-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome / Razão Social')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço da Instalação')),
                ('inverter_model', models.CharField(default='GoodWe GW5000D-NS', max_length=100, verbose_name='Modelo do Inversor')),
                ('system_power_kwp', models.FloatField(default=5.0, verbose_name='Potência Instalada (kWp)')),
                ('energy_tariff_brl', models.FloatField(default=0.85, verbose_name='Tarifa por kWh (R$)')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consumption_kwh', models.FloatField()),
                ('solar_generation_kwh', models.FloatField(default=0.0)),
                ('estimated_cost_brl', models.FloatField()),
            ],
        ),
    ]
